version: '3'
services:
  mysql:
    image: mysql:8.0.19
    ports:
      - '3306:3306'
    volumes:
      - ./resources:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass


